### ISSUE TITLE
Issue with the dependencies

### ISSUE THREAD

**Issue by swarada96** [AryanShekarlaban/data2vec-pytorch#16]
![Untitled](https://user-images.githubusercontent.com/52016562/233025806-1a7be6f5-be79-42c4-853b-ab578eb69971.png)
 Are there any other dependencies that need to be downloaded

**Comment by arxyzan** [comment]
Hello @swarada96, I'm not sure what the cause of this error might be but as far as I know, there's no additional dependency other than the ones in the `requirements.txt` file
