### ISSUE TITLE
question about disabling gradient bp

### ISSUE THREAD

**Issue by XiaoyuShi97** [AryanShekarlaban/data2vec-pytorch#8]
https://github.com/facebookresearch/fairseq/blob/main/fairseq/modules/ema_module.py#L41
Hi. It seems you forget this line, which may also disable gradient bp of the student encoder? Thx!

**Comment by btwbtm** [comment]
你好，这是石晓宇的邮箱。我会尽快处理该邮件

**Comment by arxyzan** [comment]
Hello Xiaoyu, thanks for your suggestion. I fixed the issue!
